auth.py
# auth.py

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from include.models import User
from run import db
from include.DAO import( get_user_by_email, 
insert_trader, 
insert_investigador
) 
from include.DAO_EVENTOS import (insert_error_login, 
insert_error_registrar, 
insert_evento_registro,
insert_evento_logout,
insert_evento_login
) 


auth = Blueprint('auth', __name__, url_prefix= '')

@auth.route('/login')
def login():
    return render_template('accounts/login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    correo = request.form.get('correo')
    contraseña = request.form.get('contraseña')
    remember = True if request.form.get('remember') else False

    user = get_user_by_email(correo)

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.contrasena, contraseña):
        insert_error_login('error','error')
        return render_template('accounts/login.html',
                               msg='Correo o Contraseña invalidos') # if user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    if user.tipoUsuario=='Trader':
        insert_evento_login()
        return redirect(url_for('main.profile'))
    else:
        insert_evento_login()
        return redirect(url_for('main.profile_investigador'))

@auth.route('/signup')
def signup():
    return render_template('accounts/register.html')

@auth.route('/signup', methods=['POST'])
def signup_post():

    nombre = request.form['nombre']
    apellido = request.form['apellido']
    telefono = request.form['telefono']
    contraseña = request.form['contraseña']
    correo = request.form['correo']
    tipo = 'Trader'
    
    user = get_user_by_email(correo) # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        insert_error_registrar('error','error')
        return render_template('accounts/register.html',
                               msg='Ese correo ya existe')

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(correoUsuario=correo, nombreUsuario=nombre,apellidoUsuario=apellido,telefonoUsuario=telefono, contrasena=generate_password_hash(contraseña, method='sha256'), tipoUsuario=tipo, estatusUsuario=1)

    # add the new user to the database
    insert_trader(new_user)
    user = get_user_by_email(correo)
    user_id = user.id
    insert_evento_registro(user_id,tipo)
    return render_template('accounts/login.html', msg='¡Listo! Cuenta Creada' )

@auth.route('/investigador')
def investigador():
    return render_template('accounts/register_invest.html')

@auth.route('/investigador', methods=['POST'])
def investigador_post():

    nombre = request.form['nombre']
    apellido = request.form['apellido']
    telefono = request.form['telefono']
    contraseña = request.form['contraseña']
    correo = request.form['correo']
    tipo = 'Investigador'
    
    user = get_user_by_email(correo) # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again  
        insert_error_registrar('error','error')
        return render_template('accounts/register_invest.html',
                               msg='Ese correo ya existe')

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(correoUsuario=correo, nombreUsuario=nombre,apellidoUsuario=apellido,telefonoUsuario=telefono, contrasena=generate_password_hash(contraseña, method='sha256'), tipoUsuario=tipo, estatusUsuario=1)

    # add the new user to the database
    insert_investigador(new_user)
    user = get_user_by_email(correo)
    user_id = user.id
    insert_evento_registro(user_id,tipo)  
    return render_template('accounts/login.html', msg='¡Listo! Cuenta Creada' )

@auth.route('/logout')
@login_required
def logout():
    insert_evento_logout()
    logout_user()
    return redirect(url_for('main.index'))

templates/accounts/cryptos.html
{% extends "layouts/base_trader.html" %}

{% block title %}{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!--Dashboard-->
    <div class="col-12 mb-4">
        <div class="card border-0 shadow">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col">
                        <h2 class="fs-5 fw-bold mb-0">Criptomonedas</h2>
                    </div>
                </div>
                <div class="row">
                    {% for crypto in cryptos %}
                    <div class="col-12 col-sm-6 col-xl-4 mb-4">
                        <div class="col-12 mb-4">
                            <div>
                                <div class="card">
                                    <a href="/art-trader/{{ crypto.link }}">
                                    <img class="mx-auto row align-items-center" src="{{ crypto.fotoCrypto }}" title='{{crypto.nombreCriptomoneda}}' height="250" width="250">
                                    </a>
                                    <div class="">
                                        <a class="card-body fs-5 fw-bold mb-0 col d-block d-xl-flex align-items-center" href="/art-trader/{{ crypto.link }}">Conoce a {{ crypto.nombreCriptomoneda }}</a>
                                        <div class="card border-0 shadow">
                                            <div class="card-body">
                                                <!--span class="badge bg-success">Good crypto</span-->
                                           </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
        
                </div>
            </div>
        </div>
    </div>
    

    <!--fontawesom script cdn-->
    <script src="https://use.fontawesome.com/058028e14d.js"></script>
    <script src="/static/assets/js/cryptoprice.js"></script>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/editar.html
{% extends "layouts/base_invest.html" %}

{% block title %}{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  
    <div class="perfil">
        <div class="col-12 col-xl-4-profile">
            <div class="perfil">
                <form method="POST" action="" class="mt-4">
                    <!--div class="form-group mb-4"-->
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="textarea">Publicar Artículo</label>
                                <input type="text" class="form-control" id="titulo" placeholder="Título" name="titulo" required value="{{ articulo.nombreArticulo }}"> 
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="last_name">Cryptomoneda Relacionada</label>
                                <select class="form-select mb-0" name="crypto" id="crypto" disabled aria-label="Cryptomoneda" >
                                    <option value="">{{articulo.cryptoRelacionada}}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                        <div class="input-group">
                            <textarea class="form-control" placeholder="Ingresa algo para publicar..." name="publicación"  id="textarea" rows="4">{{articulo.articulo}}</textarea>                      
                        </div>
                        <!--div class="col-md-6 mb-3">
                            <select aria-placeholder="Selecciona la cryptomoneda relacionada" class="form-select mb-0" id="gender" aria-label="Gender select example">
                                <option selected>Gender</option>
                                <option value="1">Female</option>
                                <option value="2">Male</option>
                            </select>
                        </div-->
                        <div>
                            <li role="separator" class="dropdown-divider mt-4 mb-3 "></li>
                        </div>
                    <div>
                        <button class="btn btn-sm btn-gray-800 d-inline-flex align-items-center me-2" type="submit">
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="floppy-disk"  class="icon icon-xs me-1" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M433.1 129.1l-83.9-83.9C342.3 38.32 327.1 32 316.1 32H64C28.65 32 0 60.65 0 96v320c0 35.35 28.65 64 64 64h320c35.35 0 64-28.65 64-64V163.9C448 152.9 441.7 137.7 433.1 129.1zM224 416c-35.34 0-64-28.66-64-64s28.66-64 64-64s64 28.66 64 64S259.3 416 224 416zM320 208C320 216.8 312.8 224 304 224h-224C71.16 224 64 216.8 64 208v-96C64 103.2 71.16 96 80 96h224C312.8 96 320 103.2 320 112V208z"></path></svg>
                            Publicar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
   
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script >
    const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-primary',
                cancelButton: 'btn btn-gray'
            },
            buttonsStyling: false
        });
        const form = document.getElementById('form');
    form.addEventListener('submit', function () {
            swalWithBootstrapButtons.fire({
                icon: 'success',
                title: 'Success alert',
                text: 'Artículo Guardado exitosamente !',
                showConfirmButton: true,
                timer: 1500
            })
        });
</script>
{% endblock javascripts %}

templates/accounts/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--http://www.fundraiso.ch/wp-content/uploads/2021/04/Cryptospenden.png-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CryptoMunity</title>
    <link rel="stylesheet" href="/static/assets/css/landing.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon/logo.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon/logo.png">
</head>
<body>
    <div class="hero"> 
        <div class="navbar">    
            <a class="text-white h1">     
                <img height="50" src="/static/assets/img/favicon/logo.svg" class="float-left"> 
                CryptoMunity
            </a>    
        </div>
        <div class="content"> 
            <h1 class="display-4">Bienvenidos a </h1>
            <h1 class="display-4">CryptoMunity</h1>
            <p class="p">CryptoMunity es un lugar para conocer y aprender sobre las criptomonedas. <br> Nuestra tarea es brindarte la mejor información y ranking de criptomonedas <br> para que puedas tomar la mejor desición.</p>
            <a href="/login">
                <button type="button" class="btn text-white btn-outline-secondary rounded-pill">Comenzar</button> 
            </a>
        </div>

        <div class="bubbles"> 
            <img src="https://cryptologos.cc/logos/pancakeswap-cake-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/tether-usdt-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/dogecoin-doge-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/decentraland-mana-logo.svg?v=014"> 
            <img src="https://cryptologos.cc/logos/polkadot-new-dot-logo.svg?v=014"> 
        </div>

    </div>
</body>
</html>

templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Log In {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="background-login vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container min-vh-100 min-vw-100    col-12 d-flex align-items-center justify-content-center">
                <div class="row justify-content-center form-bg-image">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    CryptoMunity - Log In
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                    
                                    {% endif %}                                     
                                </p> 
                            </div>
                            <form method="POST" action="{{ url_for('auth.login') }}" class="mt-4">
                                

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Usuario</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-user-circle"></span>
                                        </span>
                                        <input name="correo" type="email" placeholder="Correo", class="form-control" required>

                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Contraseña</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                            <input placeholder="Contraseña" class="form-control" type="password" name="contraseña" required>
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-flex justify-content-between align-items-top mb-4">
                                        <div class="form-check">
                                            <!--input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                              Recordar usuario
                                            </label-->
                                        </div> 
                                        <!--div><a href="/page-forgot-password.html" class="small text-right">Recuperar contraseña</a></div-->
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="login" class="btn btn-gray-800">Log in</button>
                                </div>
                            </form>
                            <br />
                    
                            <div class="d-flex align-items-center mt-4">
                                <span class="fw-normal">                                
                                    <a href="{{ url_for('auth.signup') }}" class="fw-bold blockquote blockquote-footer">Registrarme ahora</a>
                                    <!--a href="{{ url_for('auth.investigador') }}" class="fw-bold  p-sm-4">Investigador</a-->
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bubbles"> 
                <img src="https://cryptologos.cc/logos/pancakeswap-cake-logo.svg?v=014"> 
                <img src="https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=014"> 
                <img src=""> 
                <img src=""> 
                <img src=""> 
                <img src="https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=014"> 
                <img src="https://cryptologos.cc/logos/polkadot-new-dot-logo.svg?v=014"> 
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign Up {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="background-login vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container min-vh-100 min-vw-100    col-12 d-flex align-items-center justify-content-center">
                <div class="row justify-content-center form-bg-image">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    CryptoMunity - Sign Up
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Trader
                                    {% endif %}                                     
                                </p> 
                            </div>
                            <form method="post" action="" id="form" class="mt-4">
                                

                                <div class="form-group mb-4">
                                    <label for="email">Nombre</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-user-circle"></span>
                                        </span>
                                        <input placeholder="Nombre" name="nombre" class="form-control" type="text" required>
                                    </div>  
                                </div>
                                <div class="form-group mb-4">
                                    <label for="email">Apellido</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-user-circle"></span>
                                        </span>
                                        <input placeholder="Apellido", class="form-control" type="text" name="apellido" required>
                                    </div>  
                                </div>
                                <div class="form-group mb-4">
                                    <label for="tel">Telefono</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-solid fa-phone"></span>
                                        </span>
                                        <input placeholder="Telefono", class="form-control" type="tel" minlength="10" name="telefono" required>
                                    </div>  
                                </div>

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Correo</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-envelope"></span>
                                        </span>
                                        <input placeholder="Correo" name="correo" class="input form-control" type="email" required>
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Contraseña</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                            <input placeholder="Contraseña" name="contraseña" class="form-control" type="password" required minlength="10">
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="register" class="btn btn-gray-800">Crear cuenta</button>
                                </div>
                            </form>
                            <br />
                            

                            <!--
                            <div class="mt-3 mb-4 text-center">
                                <span class="fw-normal">or login with</span>
                            </div>
                            <div class="d-flex justify-content-center my-4">
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="facebook button" title="facebook button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
                                </a>
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="twitter button" title="twitter button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg>
                                </a>
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500" aria-label="github button" title="github button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
                                </a>
                            </div>-->



                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Ya tengo una cuenta 
                                    <a href="{{ url_for('auth.login') }}" class="fw-bold">Sing in</a>
                                </span>
                            </div>
                            <div class="d-flex align-items-center mt-4">
                                <span class="fw-normal">                                
                                    <!--a href="{{ url_for('auth.signup') }}" class="fw-bold blockquote blockquote-footer">Registrarme ahora</a-->
                                    <a id="investigador" class="fw-bold blockquote blockquote-footer">¿Quiéres ser investigador?</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bubbles"> 
                <img src="https://cryptologos.cc/logos/pancakeswap-cake-logo.svg?v=014"> 
                <img src="https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=014"> 
                <img src=""> 
                <img src=""> 
                <img src=""> 
                <img src="https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=014"> 
                <img src="https://cryptologos.cc/logos/polkadot-new-dot-logo.svg?v=014"> 
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script >
    const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-primary',
                cancelButton: 'btn btn-gray'
            },
            buttonsStyling: false
        });
        const form = document.getElementById('form');
    form.addEventListener('submit', function () {
            swalWithBootstrapButtons.fire({
                icon: 'success',
                title: 'Success alert',
                text: '¡Cuenta creada!',
                showConfirmButton: true,
                timer: 1500
            })
        });
</script>

<script>
    const investigador = document.getElementById('investigador');
    investigador.addEventListener('click', function () {
        Swal.fire({
    title:'¿Quieres ser investigador?',
    text: 'Un investigador es un experto que ayuda a la comunidad a aprender sobre las Criptomonedas escribiendo artículos',
    showCancelButton: true, 
    confirmButtonText: 'Sí quiero',
    }).then((result) => {
    /* Read more about isConfirmed, isDenied below */
    if (result.isConfirmed) {
        window.location.href = "investigador"
    }
    })
    })

</script>
{% endblock javascripts %}