include/models.py
# models.py

from flask_login import UserMixin
from run import db

class User(UserMixin, db.Model):
    __tablename__ = 'Usuarios'
    id = db.Column('IdUsuario', db.Integer, primary_key=True)
    nombreUsuario = db.Column(db.String(100), nullable=False)
    apellidoUsuario = db.Column(db.String(100), nullable=False)
    telefonoUsuario = db.Column(db.String(100), nullable=False)
    correoUsuario = db.Column(db.String(250), unique=True, nullable=False)
    contrasena = db.Column(db.String(100))
    tipoUsuario = db.Column(db.String(250), nullable=False)
    estatusUsuario = db.Column(db.Integer, nullable=True)

class Articulos(db.Model):
    __tablename__ = 'Articulos'
    id = db.Column('IdArticulos',db.Integer, primary_key=True)
    nombreArticulo = db.Column(db.String(80), nullable=False)
    autorArticulo= db.Column(db.String(80), nullable=False)
    articulo = db.Column(db.Text, nullable=False)
    fechaDePublicacion= db.Column(db.Date, nullable=True)
    noEdicion = db.Column(db.Integer,nullable=False)
    estatusArticulo = db.Column(db.Integer, nullable=False)
    fechaEdicion = db.Column(db.Date, nullable=True)
    cryptoRelacionada = db.Column(db.String(20), nullable=False)
    idUsuario = db.Column(db.Integer, nullable=False)
    sentimiento = db.Column(db.Integer, nullable=False)
    fotoArticulo = db.Column(db.String(220), nullable=False)


class Criptomonedas(db.Model):
    __tablename__ = 'Criptomonedas'
    id = db.Column('idCriptomonedas',db.Integer, primary_key=True)
    nombreCriptomoneda = db.Column(db.String(100), nullable=False)
    link = db.Column(db.String(100), nullable=False)
    fotoCrypto = db.Column(db.String(100), nullable=False)
    descripcion = db.Column(db.String(200), nullable=False)


class Botones(db.Model):
    __tablename__ = 'Botones'
    id = db.Column('idBotones',db.Integer, primary_key=True)
    tipo = db.Column(db.String(80), nullable=False)
    clase = db.Column(db.String(80), nullable=False)
    rank = db.Column(db.String(80), nullable=False)


class Eventos(db.Model):
    __tablename__ = 'Eventos'
    id = db.Column('IdEventos',db.Integer, primary_key=True)
    nombre_evento = db.Column(db.String(80), nullable=False)
    idUsuario = db.Column(db.Integer, nullable=False)
    tipoUsuario = db.Column(db.String(50), nullable=False)
    timestamp = db.Column(db.Date, nullable=False)

class FotoArticulos(db.Model):
    __tablename__ = 'fotoArticulos'
    id = db.Column('idfotoArticulos',db.Integer, primary_key=True)
    fotoArticulos = db.Column(db.Text, nullable=False)
    clasificacionFoto = db.Column(db.Text, nullable=False)
    moneda = db.Column(db.Text, nullable=False)

    

auth.py
# auth.py

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from include.models import User
from run import db
from include.DAO import( get_user_by_email, 
insert_trader, 
insert_investigador
) 
from include.DAO_EVENTOS import (insert_error_login, 
insert_error_registrar, 
insert_evento_registro,
insert_evento_logout,
insert_evento_login
) 


auth = Blueprint('auth', __name__, url_prefix= '')

@auth.route('/login')
def login():
    return render_template('accounts/login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    correo = request.form.get('correo')
    contraseña = request.form.get('contraseña')
    remember = True if request.form.get('remember') else False

    user = get_user_by_email(correo)

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.contrasena, contraseña):
        insert_error_login('error','error')
        return render_template('accounts/login.html',
                               msg='Correo o Contraseña invalidos') # if user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    if user.tipoUsuario=='Trader':
        insert_evento_login()
        return redirect(url_for('main.profile'))
    else:
        insert_evento_login()
        return redirect(url_for('main.profile_investigador'))

@auth.route('/signup')
def signup():
    return render_template('accounts/register.html')

@auth.route('/signup', methods=['POST'])
def signup_post():

    nombre = request.form['nombre']
    apellido = request.form['apellido']
    telefono = request.form['telefono']
    contraseña = request.form['contraseña']
    correo = request.form['correo']
    tipo = 'Trader'
    
    user = get_user_by_email(correo) # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        insert_error_registrar('error','error')
        return render_template('accounts/register.html',
                               msg='Ese correo ya existe')

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(correoUsuario=correo, nombreUsuario=nombre,apellidoUsuario=apellido,telefonoUsuario=telefono, contrasena=generate_password_hash(contraseña, method='sha256'), tipoUsuario=tipo, estatusUsuario=1)

    # add the new user to the database
    insert_trader(new_user)
    user = get_user_by_email(correo)
    user_id = user.id
    insert_evento_registro(user_id,tipo)
    return render_template('accounts/login.html', msg='¡Listo! Cuenta Creada' )

@auth.route('/investigador')
def investigador():
    return render_template('accounts/register_invest.html')

@auth.route('/investigador', methods=['POST'])
def investigador_post():

    nombre = request.form['nombre']
    apellido = request.form['apellido']
    telefono = request.form['telefono']
    contraseña = request.form['contraseña']
    correo = request.form['correo']
    tipo = 'Investigador'
    
    user = get_user_by_email(correo) # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again  
        insert_error_registrar('error','error')
        return render_template('accounts/register_invest.html',
                               msg='Ese correo ya existe')

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(correoUsuario=correo, nombreUsuario=nombre,apellidoUsuario=apellido,telefonoUsuario=telefono, contrasena=generate_password_hash(contraseña, method='sha256'), tipoUsuario=tipo, estatusUsuario=1)

    # add the new user to the database
    insert_investigador(new_user)
    user = get_user_by_email(correo)
    user_id = user.id
    insert_evento_registro(user_id,tipo)  
    return render_template('accounts/login.html', msg='¡Listo! Cuenta Creada' )

@auth.route('/logout')
@login_required
def logout():
    insert_evento_logout()
    logout_user()
    return redirect(url_for('main.index'))

main.py
# main.py
from flask import Blueprint, render_template, request, json, redirect, url_for, jsonify
from flask_login import login_required, current_user
from include.models import Articulos
from run import db
from include.DAO import ( 
get_all_articulos, 
get_all_photos, 
get_articulos_user_by_id, 
get_photo_by_id, 
update_articulo, 
get_articulo_by_id, 
get_articulos_by_crypto,
insert_articulo,
get_crypto,
getCryptoByName,
get_all_cryptos,
) 
from include.DAO_EVENTOS import (insert_evento_login, 
insert_evento_articulo, 
insert_evento_editararticulo, 
insert_evento_nuevoarticulo,
insert_vista_editararticulo,
insert_evento_crypto,
insert_evento_perfil,
insert_evento_cryptos
) 
from sentiment import sentiment_analysis, get_authenticate_client
from include.command import check_sentimiento, check_user, promedio
import json
from voz import from_mic as voz_funct

main = Blueprint('main', __name__, url_prefix= '')


@main.route('/')
def index():
    return render_template('accounts/landingpage.html')


@main.route('/cryptomunitylan')
def landing():
    return render_template('accounts/landingpage.html', segment='profile')

@main.route('/api', methods=["GET"])
def apiConsulta():
    nombreCrypto = request.args.get("cripto")
    crypto = getCryptoByName(nombreCrypto)
    print(crypto.descripcion)
    diccionario = {"descripcion": crypto.descripcion,
                    "link": crypto.link,
    }
    return jsonify(diccionario)

@main.route('/profile')
@login_required
def profile():
    if current_user.tipoUsuario == 'Trader':
        insert_evento_perfil()
        cryptos= get_all_cryptos()
        btc = get_articulos_by_crypto("BTC")
        eth = get_articulos_by_crypto("ETH")
        sol = get_articulos_by_crypto("SOL")
        doge = get_articulos_by_crypto("DOGE")
        cake = get_articulos_by_crypto("CAKE")
        cardano = get_articulos_by_crypto("ADA")

        botonBtc = promedio(btc)
        botonEth = promedio(eth)    
        botonSol = promedio(sol)
        botonDoge = promedio(doge)
        botonCake = promedio(cake)
        botonCardano = promedio(cardano)
        claseBtc = botonBtc.clase
        rankBtc = botonBtc.rank
        claseEth = botonEth.clase
        rankEth = botonEth.rank
        claseSol = botonSol.clase
        rankSol = botonSol.rank
        claseDoge = botonDoge.clase
        rankDoge = botonDoge.rank
        claseCake = botonCake.clase
        rankCake = botonCake.rank
        claseAda = botonCardano.clase
        rankAda = botonCardano.rank

        return render_template('accounts/profile_trader.html', name=current_user.nombreUsuario, segment='profile', claseBtc = claseBtc, rankBtc = rankBtc, claseEth = claseEth, rankEth = rankEth, claseSol = claseSol, rankSol = rankSol, claseDoge = claseDoge, rankDoge = rankDoge, claseCake = claseCake, rankCake = rankCake, claseAda = claseAda, rankAda = rankAda, cryptos=cryptos )
    else:
        insert_evento_perfil()
        return redirect(url_for('main.profile_investigador'))

@main.route('/cryptos')
@login_required
def cryptomonedas():
    if current_user.tipoUsuario == 'Trader':
        cryptos= get_all_cryptos()
        insert_evento_cryptos()
        return render_template('accounts/cryptos.html', name=current_user.nombreUsuario, segment='profile', cryptos = cryptos)
    else:
        return redirect(url_for('main.profile_investigador'))        

@main.route('/art-trader/<string:crypto>')
@login_required
def articulos_trader(crypto):
    user = check_user()
    if  user:
        pass
    else: 
        return redirect(url_for('main.profile'))  
    articulos = get_articulos_by_crypto(crypto)
    boton = promedio(articulos)
    criptomoneda = get_crypto(crypto)
    for crypto_ in criptomoneda:
        nombrecrypto = crypto_.nombreCriptomoneda
        foto = crypto_.fotoCrypto
        descripcion = crypto_.descripcion
    clase = boton.clase
    rank = boton.rank
    insert_evento_crypto()
    return render_template('accounts/trader_articulos.html', name=current_user.nombreUsuario, segment='profile', articulos_crypto=articulos, nombrecrypto=nombrecrypto, fotocrypto=foto, descripcion=descripcion, clase=clase, rank=rank)

@main.route('/profile_investigador')
@login_required
def profile_investigador():
    user = check_user()
    if user:
        return redirect(url_for('main.profile'))
    articulos_user = get_articulos_user_by_id(current_user.id)
    #for articulos in articulos_user:
        #print(articulos.fechaDePublicacion)
    return render_template('accounts/profile_invest.html', nombre=current_user.nombreUsuario, segment='profile', articulos_user=articulos_user)

@main.route('/articulos')
@login_required
def articulos():
    user = check_user()
    if user:
        return redirect(url_for('main.profile'))
    fotos = get_all_photos()
    insert_evento_articulo()
    return render_template('accounts/agregar_articulo.html', nombre=current_user.nombreUsuario, segment='articulos', fotos=fotos)



@main.route('/articuloscrypto/<int:id>')
def leerArticulos(id):
    user = check_user()
    if  user:
        pass
    else: 
        return redirect(url_for('main.profile'))
    articulo = get_articulo_by_id(id)
    return render_template('accounts/leerarticulos.html', segment='articulos', articulo=articulo)



@main.route('/articulos', methods=['POST'])
@login_required
def articulos_post():
    user = check_user()
    if user:
        return redirect(url_for('main.profile'))
    publicación = request.form['publicación']
    titulo = request.form['titulo']
    crypto = request.form['crypto']
    imagen = request.form['img']
    cliente = get_authenticate_client()
    sentimiento = sentiment_analysis(cliente,publicación)
    valoración =  check_sentimiento(sentimiento)


    nuevo_articulo= Articulos(nombreArticulo=titulo, autorArticulo=current_user.nombreUsuario,articulo=publicación,noEdicion=1,estatusArticulo=1,cryptoRelacionada=crypto,idUsuario=current_user.id,sentimiento= valoración,fotoArticulo=str(imagen))
    insert_articulo(nuevo_articulo)
    insert_evento_nuevoarticulo()
    return redirect(url_for('main.profile'))


@main.route('/articulos/edit/<int:id>')
@login_required
def articulos_edit(id):
    user = check_user()
    if user:
        return redirect(url_for('main.profile'))
    articulo = get_articulo_by_id(id)
    print(articulo.cryptoRelacionada)
    insert_vista_editararticulo
    return render_template('accounts/editar.html', segment='articulos', articulo=articulo)

@main.route('/articulos/edit/<int:id>', methods=['POST'])
@login_required
def articulos_edit_post(id):
    user = check_user()
    if user:
        return redirect(url_for('main.profile'))
    publicación = request.form['publicación']
    titulo = request.form['titulo']
    cliente = get_authenticate_client()
    sentimiento = sentiment_analysis(cliente,publicación)
    valoración =  check_sentimiento(sentimiento)
    update_articulo(id,titulo,publicación,valoración)
    insert_evento_editararticulo()
    return redirect(url_for('main.profile'))

@main.route('/voz', methods=['POST'])
@login_required
def voz():
    texto = voz_funct()
    texto_json = {
        "speech": texto
    }
    print(texto)
    return jsonify(texto_json)

templates/includes/navigation_invest.html
<nav class="d-md-block bg-primary text-white collapse px-4  navbar-top navbar-expand navbar-dark pl-0 pr-2 pb-0">
  <div class="d-flex w-100" id="navbarSupportedContent">
    <!-- Navbar links -->
    <ul class="navbar-nav d-flex w-50 align-items-center">
      <!--CryptoMunity-->
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="/profile">
          <span class="sidebar-icon">
            <img src="/static/assets/img/favicon/logo.png" height="20" width="20" alt="cryptomunity">
          </span>
          <span class="mt-1 ms-1 sidebar-text">CryptoMunity</span>
        </a>
      </li>
      <!--Añadir articulo-->
      <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
        <a href="{{ url_for('main.articulos') }}" class="nav-link">
          <span class="sidebar-icon">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="file-lines" class="icon icon-xs me-2" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="currentColor" d="M256 0v128h128L256 0zM224 128L224 0H48C21.49 0 0 21.49 0 48v416C0 490.5 21.49 512 48 512h288c26.51 0 48-21.49 48-48V160h-127.1C238.3 160 224 145.7 224 128zM272 416h-160C103.2 416 96 408.8 96 400C96 391.2 103.2 384 112 384h160c8.836 0 16 7.162 16 16C288 408.8 280.8 416 272 416zM272 352h-160C103.2 352 96 344.8 96 336C96 327.2 103.2 320 112 320h160c8.836 0 16 7.162 16 16C288 344.8 280.8 352 272 352zM288 272C288 280.8 280.8 288 272 288h-160C103.2 288 96 280.8 96 272C96 263.2 103.2 256 112 256h160C280.8 256 288 263.2 288 272z"></path></svg>
          </span>
          <span class="sidebar-text">Añadir Artículo</span>
        </a>
      </li> 
    </ul>

    <ul class="navbar-nav d-flex w-100 justify-content-end align-items-center">
      <!--Profile-->
      <div class="justify-content-between">
      </div>
      <!--Notificatios-->
      <li class="nav-item dropdown">
        <a class="nav-link text-dark notification-bell  dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
          <svg class="icon icon-sm text-white-900" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
          <div class="list-group list-group-flush">
            <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">No tienes notificaciones</a>
          </div>
        </div>
      </li>
      <!--User-->
      <li class="nav-item dropdown ms-lg-3">
        <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="media d-flex align-items-center">
            <img class="avatar rounded-circle" alt="Image placeholder" src="/static/assets/img/trader.png">
            <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
              <span class="mb-0 font-small fw-bold text-white-900">
                <strong>{{ current_user.nombreUsuario }}</strong>
              </span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
          <a class="dropdown-item d-flex align-items-center text-primary" href="{{ url_for('main.profile') }}">
            <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
            My Profile
          </a>
          <div role="separator" class="dropdown-divider my-1"></div>
          <a class="dropdown-item d-flex align-items-center text-primary" href="{{ url_for('auth.logout') }}">
            <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
            Logout
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

templates/includes/navigation_trader.html
<nav class="d-md-block bg-primary text-white collapse px-4  navbar-top navbar-expand navbar-dark pl-0 pr-2 pb-0">
  <div class="d-flex w-100" id="navbarSupportedContent">
    <!-- Navbar links -->
    <ul class="navbar-nav d-flex w-50 align-items-center">
      <!--CryptoMunity-->
      <li class="nav-item">
        <a class="nav-link d-flex align-items-center" href="/profile">
          <span class="sidebar-icon">
            <img src="/static/assets/img/favicon/logo.png" height="20" width="20" alt="cryptomunity">
          </span>
          <span class="mt-1 ms-1 sidebar-text">CryptoMunity</span>
        </a>
      </li>
      <!--MENU-->
      <!--li class="nav-item {% if 'settings' in segment %} active {% endif %}">
        <a href="{{ url_for('main.profile') }}" class="nav-link">
          <span class="sidebar-icon">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="house" class="icon icon-xs me-2" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M575.8 255.5C575.8 273.5 560.8 287.6 543.8 287.6H511.8L512.5 447.7C512.5 450.5 512.3 453.1 512 455.8V472C512 494.1 494.1 512 472 512H456C454.9 512 453.8 511.1 452.7 511.9C451.3 511.1 449.9 512 448.5 512H392C369.9 512 352 494.1 352 472V384C352 366.3 337.7 352 320 352H256C238.3 352 224 366.3 224 384V472C224 494.1 206.1 512 184 512H128.1C126.6 512 125.1 511.9 123.6 511.8C122.4 511.9 121.2 512 120 512H104C81.91 512 64 494.1 64 472V360C64 359.1 64.03 358.1 64.09 357.2V287.6H32.05C14.02 287.6 0 273.5 0 255.5C0 246.5 3.004 238.5 10.01 231.5L266.4 8.016C273.4 1.002 281.4 0 288.4 0C295.4 0 303.4 2.004 309.5 7.014L564.8 231.5C572.8 238.5 576.9 246.5 575.8 255.5L575.8 255.5z"></path></svg>
          </span>
          <span class="sidebar-text">Menú</span>
        </a>
      </li--> 
      <!--Cryptos-->
      <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
        <a href="{{ url_for('main.cryptomonedas') }}" class="nav-link">
          <span class="sidebar-icon">
            <svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="bitcoin" class="icon icon-xs me-2" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M504 256c0 136.1-111 248-248 248S8 392.1 8 256 119 8 256 8s248 111 248 248zm-141.7-35.33c4.937-32.1-20.19-50.74-54.55-62.57l11.15-44.7-27.21-6.781-10.85 43.52c-7.154-1.783-14.5-3.464-21.8-5.13l10.93-43.81-27.2-6.781-11.15 44.69c-5.922-1.349-11.73-2.682-17.38-4.084l.031-.14-37.53-9.37-7.239 29.06s20.19 4.627 19.76 4.913c11.02 2.751 13.01 10.04 12.68 15.82l-12.7 50.92c.76 .194 1.744 .473 2.829 .907-.907-.225-1.876-.473-2.876-.713l-17.8 71.34c-1.349 3.348-4.767 8.37-12.47 6.464 .271 .395-19.78-4.937-19.78-4.937l-13.51 31.15 35.41 8.827c6.588 1.651 13.05 3.379 19.4 5.006l-11.26 45.21 27.18 6.781 11.15-44.73a1038 1038 0 0 0 21.69 5.627l-11.11 44.52 27.21 6.781 11.26-45.13c46.4 8.781 81.3 5.239 95.99-36.73 11.84-33.79-.589-53.28-25-65.99 17.78-4.098 31.17-15.79 34.75-39.95zm-62.18 87.18c-8.41 33.79-65.31 15.52-83.75 10.94l14.94-59.9c18.45 4.603 77.6 13.72 68.81 48.96zm8.417-87.67c-7.673 30.74-55.03 15.12-70.39 11.29l13.55-54.33c15.36 3.828 64.84 10.97 56.85 43.03z"></path></svg>
          </span>
          <span class="sidebar-text">Cryptos</span>
        </a>
      </li> 
    </ul>

    <ul class="navbar-nav d-flex w-100 justify-content-end align-items-center">
      <!--Profile-->
      <div class="justify-content-between">


      </div>
      <!--Notificatios-->
      <li class="nav-item dropdown">
        <a class="nav-link text-dark notification-bell  dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
          <svg class="icon icon-sm text-white-900" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
          <div class="list-group list-group-flush">
            <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">No tienes notificaciones</a>
          </div>
        </div>
      </li>
      <!--User-->
      <li class="nav-item dropdown ms-lg-3">
        <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="media d-flex align-items-center">
            <img class="avatar rounded-circle" alt="Image placeholder" src="/static/assets/img/trader.png">
            <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
              <span class="mb-0 font-small fw-bold text-white-900">
                <strong>{{ current_user.nombreUsuario }}</strong>
              </span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
          <a class="dropdown-item d-flex align-items-center text-primary" href="{{ url_for('main.profile') }}">
            <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
            My Profile
          </a>
          <div role="separator" class="dropdown-divider my-1"></div>
          <a class="dropdown-item d-flex align-items-center text-primary" href="{{ url_for('auth.logout') }}">
            <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
            Logout
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>